CREATE TABLE IF NOT EXISTS views (
    id SERIAL PRIMARY KEY,
    date DATE DEFAULT CURRENT_DATE,
    news_id INTEGER,
    videos_id INTEGER
);

ALTER TABLE views ADD COLUMN IF NOT EXISTS news_id INTEGER;
ALTER TABLE views ADD COLUMN IF NOT EXISTS videos_id INTEGER;
